[project]
name = "network-security-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "seaborn",
    "matplotlib",
    "matplotlib-inline",
    "ipython",
    "pygments",
    "imblearn",
    "pyarrow>=25.0.1",
    "certifi>=2026.7.22",
    "duckdb>=1.5.6",
    "scapy>=2.8.0",
]
